services:
  - type: web
    name: cricscore-api
    env: node
    plan: free
    region: singapore
    buildCommand: npm install && npx prisma generate && npm run build:backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        sync: false  # You will set this manually in dashboard
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FIREBASE_ADMIN_SDK_CONFIG
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
